server:
  port: 7003
  error:
    include-message: always

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db
