server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

spring.data.mongodb.host: mongodb