server:
  port: 7001

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080